#!/usr/bin/env python3
"""Generate P10-1 discovery, documentation, and console projections."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from live_mem.tools.exposure import (  # noqa: E402
    DISCOVERY_NAMES_BY_PERMISSION,
    TOOL_EXPOSURES,
    ToolPermission,
    console_capability_manifest,
    exposure_manifest,
    registered_exposure_names,
)


def render_discovery_fixture() -> str:
    manifest = exposure_manifest()
    # Full registration counts are expected only by tool_surface.json. This
    # fixture owns discovery/exposure projections, not a second surface total.
    manifest.pop("registered_total")
    manifest.pop("registry_entries")
    return json.dumps(
        manifest,
        ensure_ascii=False,
        indent=2,
        sort_keys=False,
    ) + "\n"


def render_inventory_doc() -> str:
    lines = [
        "# MCP Tool Exposure Inventory",
        "",
        "<!-- Generated by scripts/generate_tool_exposure.py; do not edit. -->",
        "",
        "`ToolExposure` is an exposure and rendering contract, not an authorization",
        "source. Every handler still enforces its own fresh call-time guards.",
        "",
        "## Discovery profiles",
        "",
        "| Effective permission | Count | Advertised canonical names |",
        "|---|---:|---|",
    ]
    for permission in (
        ToolPermission.READ,
        ToolPermission.WRITE,
        ToolPermission.MANAGE,
        ToolPermission.ADMIN,
    ):
        names = DISCOVERY_NAMES_BY_PERMISSION[permission]
        rendered = ", ".join(f"`{name}`" for name in names)
        lines.append(f"| `{permission.value}` | {len(names)} | {rendered} |")

    lines.extend(
        [
            "",
            "Historical aliases and operator tools remain registered and callable by",
            "exact name, subject to their handler authorization, but are not advertised",
            "by regular MCP discovery.",
            "",
            "## Complete registered surface",
            "",
            f"{len(TOOL_EXPOSURES)} registry entries cover "
            f"{len(registered_exposure_names())} registered names.",
            "",
            "| Canonical name | Historical aliases | Audience | Minimum profile | Operation | Space-scope argument |",
            "|---|---|---|---|---|---|",
        ]
    )
    for entry in TOOL_EXPOSURES:
        aliases = ", ".join(f"`{alias}`" for alias in entry.aliases) or "—"
        scope = (
            f"`{entry.space_scope_argument}`"
            if entry.space_scope_argument is not None
            else "—"
        )
        lines.append(
            f"| `{entry.canonical_name}` | {aliases} | `{entry.audience.value}` | "
            f"`{entry.minimum_permission.value}` | `{entry.operation.value}` | "
            f"{scope} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_console_capabilities() -> str:
    by_name = console_capability_manifest()
    payload = json.dumps(by_name, ensure_ascii=False, indent=2, sort_keys=False)
    return (
        "/* Generated by scripts/generate_tool_exposure.py; do not edit.\n"
        " * UI capability hints only. Server-side tool guards are authoritative.\n"
        " */\n"
        f"const HIVEMIND_TOOL_CAPABILITIES = Object.freeze({payload});\n"
    )


ARTIFACTS = {
    REPO_ROOT / "tests" / "fixtures" / "tool_discovery.json": (
        render_discovery_fixture
    ),
    REPO_ROOT / "docs" / "TOOL_EXPOSURE.md": render_inventory_doc,
    REPO_ROOT
    / "src"
    / "live_mem"
    / "static"
    / "js"
    / "admin-tool-capabilities.generated.js": render_console_capabilities,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)

    stale: list[str] = []
    for path, renderer in ARTIFACTS.items():
        expected = renderer()
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")
            continue
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path.relative_to(REPO_ROOT).as_posix())

    if stale:
        print("stale generated ToolExposure artifacts:", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
